version: '3.8'

services:
  backend:
    build: ./server
    container_name: flask-backend
    ports:
      - "5001:5001"

  frontend:
    build: ./client
    container_name: vue-frontend
    ports:
      - "5173:5173"

    depends_on:
      - backend
