version: '3.8'

services:
  backend:
    image: vijay171202/backend:latest
    container_name: backend
    restart: always
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    image: vijay171202/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - app-network


